# NumPy - Numrical Python


Advantages of Numpy Arryas

    1.Allows several marhematical operation
    2.faster operations

In [1]:
import numpy as np

List vs Numpy - time taken

In [2]:
from time import process_time

Time taken by list

Use google colab 

In [4]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0


In [5]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0


Numpy array

In [6]:
#list
list1 = [1,2,3,4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [10]:
#creating 1-D array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [11]:
#creating 2-D array
b = np.array([(1,2,3),(9,6,8)])
print (b)

[[1 2 3]
 [9 6 8]]


In [13]:
#to find the number of rows and columns
b.shape

(2, 3)

In [15]:
#By default the data type is in int 
c = np.array([(1,2,3,4),(7,8,9,4)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [7. 8. 9. 4.]]


numpy.ndarray

Initial placeholders in numpy arrays 

In [16]:
#create a numpy array of zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
#create a numpy array of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# array of a particular value
z= np.full((5,4),5)
print (z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [21]:
# create an identity matrix (number of rows and columns should be equal)
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
#create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.11953248 0.10838686 0.83107291 0.30446012]
 [0.61280552 0.36813448 0.25217344 0.41158576]
 [0.19348611 0.82923375 0.42727204 0.64360628]]


In [25]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[22 63 82 14 62]
 [14 93 69 32 30]
 [37 39 25 76 38]]


In [29]:
# array of evenly spaced values --- specifing the number of values we want
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [31]:
# array of evenly spaced values --- specifing the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [32]:
# convert a list into np array
list2=[10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numy array

In [33]:
c = np.random.randint(10,90,(5,5))
print(c)

[[31 87 43 76 54]
 [29 76 51 56 32]
 [40 82 79 42 76]
 [64 62 45 10 68]
 [12 27 33 62 71]]


In [34]:
# Array dimension
print(c.shape)

(5, 5)


In [35]:
# Number of dimension
print(c.ndim)

2


In [36]:
# number of elements in an array
print(c.size)

25


In [37]:
# checking the datatype of the values in the array
print(c.dtype)

int32


Mathematical operation on a np array

In [38]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print (list1 + list2) #concatinate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [39]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [40]:
print(a)
print(b)

[[9 9 3]
 [6 4 5]
 [5 7 8]]
[[17 13 14]
 [14 13 13]
 [16 11 10]]


In [41]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[26 22 17]
 [20 17 18]
 [21 18 18]]
[[ -8  -4 -11]
 [ -8  -9  -8]
 [-11  -4  -2]]
[[153 117  42]
 [ 84  52  65]
 [ 80  77  80]]
[[0.52941176 0.69230769 0.21428571]
 [0.42857143 0.30769231 0.38461538]
 [0.3125     0.63636364 0.8       ]]


In [42]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [44]:
print(a)
print(b)

[[0 4 8]
 [8 8 8]
 [9 2 4]]
[[14 15 15]
 [14 16 12]
 [19 12 17]]


In [46]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[14 19 23]
 [22 24 20]
 [28 14 21]]
[[-14 -11  -7]
 [ -6  -8  -4]
 [-10 -10 -13]]
[[  0  60 120]
 [112 128  96]
 [171  24  68]]
[[0.         0.26666667 0.53333333]
 [0.57142857 0.5        0.66666667]
 [0.47368421 0.16666667 0.23529412]]


In [47]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 0 4]
 [3 6 1]]
(2, 3)


In [48]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[7 3]
 [0 6]
 [4 1]]
(3, 2)


In [49]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 3 6]
 [5 3 7]]
(2, 3)


In [50]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[2 5]
 [3 3]
 [6 7]]
(3, 2)


In [51]:
# reshaping the array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 8 7]
 [7 4 8]]
(2, 3)


In [55]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 8]
 [7 7]
 [4 8]]
(3, 2)
